// browser/create-template/templates/nextjs-site/src/components/Footer.tsx
import Container from "./Layout/Container";
import styles from "./Footer.module.css";

const Footer = () => {
  const year = new Date().getFullYear();
  return (
    <footer className={styles.footer}>
      <Container>
        <p>&copy; {year} Your Company</p>
      </Container>
    </footer>
  );
};

export default Footer;

// browser/create-template/templates/sveltekit-site/src/lib/components/Footer.svelte
<script lang="ts">
	import Container from './Layout/Container.svelte';

	const year = new Date().getFullYear();
</script>

<footer>
	<Container>
		<p>© {year} Your Company</p>
	</Container>
</footer>

<style>
	footer {
		background-color: var(--theme-color-bg-2);
		color: var(--theme-color-text-light);
	}

	p {
		padding: 1rem;
	}
</style>
