// browser/create-template/templates/nextjs-site/src/views/FullPage/BlogpostFullPage.tsx
import Container from '@/components/Layout/Container';
import { Blogpost } from '@/ontologies/website';
import { Resource } from '@tomic/lib';
import styles from './BlogpostFullPage.module.css';
import { Image } from '@/components/Image';
import matter from 'gray-matter';
import html from 'remark-html';
import { remark } from 'remark';

const BlogpostFullPage = ({ resource }: { resource: Resource<Blogpost> }) => {
  const formatter = new Intl.DateTimeFormat('default', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // const date = formatter.format(new Date(resource.props.publishedAt));
  const date = '';

  const matterResult = matter(resource.props.description);
  const processed = remark().use(html).processSync(matterResult.content);
  const content = processed.toString();

  return (
    <Container>
      <div className={styles.blogWrapper}>
        <Image subject={resource.props.coverImage} alt='' />
        <div className={styles.content}>
          <h1 className={styles.h1}>{resource.title}</h1>
          <p className={styles.publishDate}>{date}</p>
          <div dangerouslySetInnerHTML={{ __html: content }} />
        </div>
      </div>
    </Container>
  );
};

export default BlogpostFullPage;

// browser/create-template/templates/sveltekit-site/src/lib/views/FullPage/BlogpostFullPage.svelte
<script lang="ts">
	import Container from '$lib/components/Layout/Container.svelte';
	import type { Blogpost } from '$lib/ontologies/website';
	import type { Resource } from '@tomic/lib';
	import { Image } from '@tomic/svelte';
	import SvelteMarkdown from 'svelte-markdown';
	import type { Readable } from 'svelte/store';

	export let resource: Readable<Resource<Blogpost>>;

	const formatter = new Intl.DateTimeFormat('default', {
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	});

	$: date = formatter.format(new Date($resource.props.publishedAt));
</script>

<Container>
	<div class="blog-wrapper">
		<Image subject={$resource.props.coverImage} alt="" />
		<div class="content">
			<h1>{$resource.title}</h1>
			<p class="publish-date">
				{date}
			</p>
			<SvelteMarkdown source={$resource.props.description} />
		</div>
	</div>
</Container>

<style>
	.blog-wrapper {
		padding: 1rem;
		& > picture > img {
			width: 100%;
			height: 25rem;
			object-fit: cover;
			border-radius: var(--theme-border-radius);
		}
	}

	.publish-date {
		color: var(--theme-color-text-light);
		margin-bottom: 2rem;
	}
	.content {
		max-width: 70ch;
		margin: auto;
	}
</style>
