// browser/create-template/templates/nextjs-site/src/views/FullPage/PageFullPage.tsx
import { core, type Resource } from '@tomic/lib';
import BlockView from '../Block/BlockView';
import { website, type Page } from '@/ontologies/website';
import styles from './PageFullPage.module.css';
import Container from '@/components/Layout/Container';

const PageFullPage = ({ resource }: { resource: Resource<Page> }) => {
  // const [title] = useValue(resource, core.properties.name);
  const title = resource.title;

  return (
    <Container>
      <div className={styles.wrapper}>
        <h1>{title?.toString()}</h1>

        {resource
          .get(website.properties.blocks)
          ?.map((block: string) => <BlockView key={block} subject={block} />)}
      </div>
    </Container>
  );
};

export default PageFullPage;

// browser/create-template/templates/sveltekit-site/src/lib/views/FullPage/PageFullPage.svelte
<script lang="ts">
	import Container from '$lib/components/Layout/Container.svelte';
	import type { Page } from '$lib/ontologies/website';
	import { core, type Resource } from '@tomic/lib';
	import BlockView from '../Block/BlockView.svelte';
	import type { Readable } from 'svelte/store';
	import { getValue } from '@tomic/svelte';

	export let resource: Readable<Resource<Page>>;

	$: title = getValue(resource, core.properties.name);
</script>

<Container>
	<div class="wrapper">
		<h1>{$title}</h1>

		{#each $resource.props.blocks ?? [] as block (block)}
			<BlockView subject={block} />
		{/each}
	</div>
</Container>

<style>
	.wrapper {
		padding: 1rem;
		display: flex;
		flex-direction: column;
		gap: 1rem;

		& h1 {
			margin: 0;
		}
	}
</style>
