// browser/create-template/templates/sveltekit-site/src/lib/components/Layout/HStack.svelte
<script lang="ts">
	export let gap = '1rem';
	export let align = 'start';
	export let justify = 'start';
	export let fullWidth = false;
	export let wrap = false;
</script>

<div
	style:--hstack-gap={gap}
	style:--hstack-align={align}
	style:--hstack-justify={justify}
	class:full-width={fullWidth}
	class:wrap
>
	<slot />
</div>

<style>
	div {
		display: flex;
		gap: var(--hstack-gap);
		align-items: var(--hstack-align);
		justify-content: var(--hstack-justify);

		& > h1,
		& > h2,
		& > h3,
		& > h4,
		& > h5,
		& > h6 {
			margin: 0;
		}
	}

	.full-width {
		width: 100%;
	}

	.wrap {
		flex-wrap: wrap;
	}
</style>

// browser/create-template/templates/nextjs-site/src/components/Layout/HStack.tsx
import React, { ReactNode } from 'react';
import clsx from 'clsx';
import styles from './HStack.module.css';

interface HStackProps {
  gap?: React.CSSProperties['gap'];
  align?: React.CSSProperties['alignItems'];
  justify?: React.CSSProperties['justifyContent'];
  fullWidth?: boolean;
  wrap?: boolean;
  children: ReactNode;
}

const HStack: React.FC<HStackProps> = ({
  gap = '1rem',
  align = 'start',
  justify = 'start',
  fullWidth = false,
  wrap = false,
  children,
}) => {
  const inlineStyles: {
    [key: string]: string | number;
  } = {
    '--hstack-gap': gap,
    '--hstack-align': align,
    '--hstack-justify': justify,
  };

  return (
    <div
      style={inlineStyles}
      className={clsx(styles.hstack, {
        [styles.fullWidth]: fullWidth,
        [styles.wrap]: wrap,
      })}
    >
      {children}
    </div>
  );
};

export default HStack;
