// browser/create-template/templates/sveltekit-site/src/lib/components/Layout/VStack.svelte
<script lang="ts">
	export let gap = '1rem';
	export let align = 'start';
	export let justify = 'start';
	export let height = 'auto';
</script>

<div
	style:--vstack-gap={gap}
	style:--vstack-align={align}
	style:--vstack-justify={justify}
	style:--vstack-height={height}
>
	<slot />
</div>

<style>
	div {
		display: flex;
		flex-direction: column;
		gap: var(--vstack-gap);
		align-items: var(--vstack-align);
		justify-content: var(--vstack-justify);
		height: var(--vstack-height);
		& > h1,
		& > h2,
		& > h3,
		& > h4,
		& > h5,
		& > h6 {
			margin: 0;
		}
	}
</style>

// browser/create-template/templates/nextjs-site/src/components/Layout/VStack.tsx
import React, { ReactNode } from "react";
import styles from "./VStack.module.css";

interface VStackProps {
  gap?: React.CSSProperties["gap"];
  align?: React.CSSProperties["alignItems"];
  justify?: React.CSSProperties["justifyContent"];
  height?: React.CSSProperties["height"];
  children: ReactNode;
}

const VStack: React.FC<VStackProps> = ({
  gap = "1rem",
  align = "start",
  justify = "start",
  height = "auto",
  children,
}) => {
  const inlineStyles: {
    [key: string]: React.CSSProperties[keyof React.CSSProperties];
  } = {
    "--vstack-gap": gap,
    "--vstack-align": align,
    "--vstack-justify": justify,
    "--vstack-height": height,
  };

  return (
    <div style={inlineStyles} className={styles.vstack}>
      {children}
    </div>
  );
};

export default VStack;
