// browser/create-template/templates/sveltekit-site/src/lib/components/Navbar.svelte
<script lang="ts">
	import { PUBLIC_WEBSITE_RESOURCE } from '$env/static/public';
	import { type Website } from '$lib/ontologies/website';
	import { getResource } from '@tomic/svelte';
	import MenuItem from '../views/MenuItem/MenuItem.svelte';
	import Container from './Layout/Container.svelte';
	import HStack from './Layout/HStack.svelte';
	import Loader from './Loader.svelte';

	$: site = getResource<Website>(PUBLIC_WEBSITE_RESOURCE);
</script>

<Container>
	<nav>
		<HStack align="center" justify="space-between" wrap>
			<Loader resource={$site}>
				<a class="site-title" href="/">
					{$site.title}
				</a>
				<ul>
					{#each $site.props.menuItems ?? [] as menuItem}
						<li>
							<MenuItem subject={menuItem} />
						</li>
					{/each}
				</ul>
			</Loader>
		</HStack>
	</nav>
</Container>

<style>
	nav {
		gap: 1rem;
		padding: 2rem 1rem;
		border-bottom: 1px solid var(--theme-color-bg-1);
	}

	ul {
		display: flex;
		list-style: none;
		padding: 0;
		margin: 0;
		gap: 1rem;
	}

	.site-title {
		font-size: 1.5rem;
		text-decoration: none;
		color: var(--theme-color-text);
	}
</style>

// browser/create-template/templates/nextjs-site/src/components/Navbar.tsx
'use client';

import { useArray, useResource } from '@tomic/react';
import Container from './Layout/Container';
import HStack from './Layout/HStack';
import { env } from '@/env';
import { website, Website } from '@/ontologies/website';
import MenuItem from '@/views/MenuItem/MenuItem';
import Loader from './Loader';
import styles from './Navbar.module.css';

const Navbar = () => {
  const site = useResource<Website>(env.NEXT_PUBLIC_WEBSITE_RESOURCE);

  return (
    <Container>
      <nav className={styles.nav}>
        <HStack align='center' justify='space-between' wrap>
          <Loader resource={site}>
            <a href='/' className={styles.title}>
              {site.title}
            </a>
            <ul className={styles.ul}>
              {site.props.menuItems?.map((menuItem: string) => (
                <li key={menuItem}>
                  <MenuItem subject={menuItem} />
                </li>
              ))}
            </ul>
          </Loader>
        </HStack>
      </nav>
    </Container>
  );
};

export default Navbar;
