// browser/create-template/templates/sveltekit-site/src/lib/views/Block/BlockView.svelte
<script lang="ts">
	import { website } from '$lib/ontologies/website';
	import { getResource } from '@tomic/svelte';
	import DefaultView from '../DefaultView.svelte';
	import TextBlock from './TextBlock.svelte';
	import ImageGalleryBlock from './ImageGalleryBlock.svelte';

	export let subject: string;
	let block = getResource(subject);

	$: component = $block.matchClass(
		{
			[website.classes.textBlock]: TextBlock,
			[website.classes.imageGalleryBlock]: ImageGalleryBlock
		},
		DefaultView
	);
</script>

<svelte:component this={component} resource={$block} />

// browser/create-template/templates/nextjs-site/src/views/Block/BlockView.tsx
import { useResource } from '@tomic/react';
import DefaultView from '../DefaultView';
import TextBlock from './TextBlock';
import { website } from '@/ontologies/website';
import ImageGalleryBlock from './ImageGalleryBlock';
import { store } from '@/app/store';

const BlockView = async ({ subject }: { subject: string }) => {
  // const block = useResource(subject);
  const block = await store.getResource(subject);

  const Component = block.matchClass(
    {
      [website.classes.textBlock]: TextBlock,
      [website.classes.imageGalleryBlock]: ImageGalleryBlock,
    },
    DefaultView,
  );

  return <Component resource={block} />;
};

export default BlockView;
