// browser/create-template/templates/sveltekit-site/src/lib/views/Block/ImageGalleryBlock.svelte
<script lang="ts">
	import { core, type Resource } from '@tomic/lib';
	import { Image } from '@tomic/svelte';
	import type { ImageGalleryBlock } from '$lib/ontologies/website';

	export let resource: Resource<ImageGalleryBlock>;
</script>

{#if resource.get(core.properties.name)}
	<h2>{resource.title}</h2>
{/if}
<div class="wrapper">
	{#each resource.props.images as image}
		<Image subject={image} alt="" />
	{/each}
</div>

<style>
	.wrapper {
		width: 100%;
		display: grid;
		grid-template-columns: repeat(
			auto-fill,
			minmax(calc(var(--theme-size-container-width) / 3 - 4rem), 1fr)
		);
		gap: 1rem;
		& img {
			aspect-ratio: 1 / 1;
			object-fit: cover;
		}
	}
</style>

// browser/create-template/templates/nextjs-site/src/views/Block/ImageGalleryBlock.tsx
import { Resource } from '@tomic/lib';
import { Image } from '@/components/Image';
import styles from './ImageGalleryBlock.module.css';
import { Suspense } from 'react';
import { website } from '@/ontologies/website';

const ImageGalleryBlock = async ({ resource }: { resource: Resource }) => {
  return (
    <>
      {resource.props.name ? <h2>{resource.props.name}</h2> : null}

      <div className={styles.wrapper}>
        {resource
          .get(website.properties.images)
          ?.map((image: string, index: number) => (
            <div key={index} className={styles.image}>
              <Image subject={image} alt='' />
            </div>
          ))}
      </div>
    </>
  );
};

export default ImageGalleryBlock;
