// browser/create-template/templates/sveltekit-site/src/lib/views/ListItem/ListItemView.svelte
<script lang="ts">
	import { website } from '$lib/ontologies/website';
	import { getResource } from '@tomic/svelte';
	import DefaultView from '../DefaultView.svelte';
	import BlogListItem from './BlogListItem.svelte';

	export let subject: string;
	let listItem = getResource(subject);

	$: component = $listItem.matchClass(
		{
			[website.classes.blogpost]: BlogListItem
		},
		DefaultView
	);
</script>

<svelte:component this={component} resource={$listItem} />

// browser/create-template/templates/nextjs-site/src/views/ListItem/ListItemView.tsx
import { useResource } from "@tomic/react";
import { website } from "@/ontologies/website";
import BlogListItem from "./BlogListItem";
import DefaultView from "@/views/DefaultView";

const ListItemView = ({ subject }: { subject: string }) => {
  const listItem = useResource(subject);

  const Component = listItem.matchClass(
    {
      [website.classes.blogpost]: BlogListItem,
    },
    DefaultView
  );

  return <Component resource={listItem} />;
};

export default ListItemView;
