// browser/create-template/templates/sveltekit-site/src/lib/views/FullPage/DefaultFullPage.svelte
<script lang="ts">
	import Container from '$lib/components/Layout/Container.svelte';
	import type { Resource } from '@tomic/lib';
	import type { Readable } from 'svelte/store';

	export let resource: Readable<Resource>;
</script>

<Container>
	<h1>{$resource.title}</h1>

	<p>No valid page view for this resource.</p>
</Container>

// browser/create-template/templates/nextjs-site/src/views/FullPage/DefaultFullPage.tsx
import Container from "@/components/Layout/Container";
import { Resource } from "@tomic/lib";

const DefaultFullPage = ({ resource }: { resource: Resource }) => {
  return (
    <Container>
      <h1>{resource.title}</h1>
      <p>No valid page view for resource {resource.getClasses()}.</p>
    </Container>
  );
};

export default DefaultFullPage;
