// browser/create-template/templates/sveltekit-site/src/lib/views/FullPage/FullPageView.svelte
<script lang="ts">
	import { website } from '$lib/ontologies/website';
	import { getResource } from '@tomic/svelte';
	import PageFullPage from './PageFullPage.svelte';
	import DefaultFullPage from './DefaultFullPage.svelte';
	import BlogIndexPageFullPage from './BlogIndexPageFullPage.svelte';
	import BlogpostFullPage from './BlogpostFullPage.svelte';

	/*
		Renders a full page view. The actual view component is determined by the resource's class.
	*/

	export let subject: string;

	$: resource = getResource(subject);

	$: component = $resource.matchClass(
		{
			[website.classes.page]: PageFullPage,
			[website.classes.blogIndexPage]: BlogIndexPageFullPage,
			[website.classes.blogpost]: BlogpostFullPage
		},
		DefaultFullPage
	);
</script>

<svelte:component this={component} {resource} />

// browser/create-template/templates/nextjs-site/src/views/FullPage/FullPageView.tsx
import { website } from '@/ontologies/website';
import PageFullPage from './PageFullPage';
import BlogIndexPageFullPage from './BlogIndexPageFullPage';
import BlogpostFullPage from './BlogpostFullPage';
import DefaultFullPage from './DefaultFullPage';
import { store } from '@/app/store';

const FullPageView = async ({ subject }: { subject: string }) => {
  const resource = await store.getResource(subject);

  const Component = resource.matchClass(
    {
      [website.classes.page]: PageFullPage,
      [website.classes.blogIndexPage]: BlogIndexPageFullPage,
      [website.classes.blogpost]: BlogpostFullPage,
    },
    DefaultFullPage,
  );

  return <Component resource={resource} />;
};

export default FullPageView;
